# backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: day4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: successtech/day3back
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              value: bob
            - name: DB_PASS
              value: password123
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: day4
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  clusterIP: None
